/* =========================================================================
   Market list — renders a grid of prediction-market cards from a static
   dataset. Card shape mirrors Figma node 16145:203087 (YES variant).

   Thumbnails are 128x128 JPEGs generated by Pollinations.ai with prompts
   tailored to each market subject (see assets/thumbs/).
   ========================================================================= */

const markets = [
  // ===== Sport =====
  {
    category: "sport",
    source: "BetZone", volume: "$4.8M", delta: "+5.4%",
    title: "Will Barcelona beat Liverpool tonight?",
    yes: 62, no: 38, timeLeft: "8d 4h left", progress: 60,
    thumb: "assets/thumbs/barcelona-liverpool.jpg",
  },
  {
    category: "sport",
    source: "BetZone", volume: "$890k", delta: "+3.1%",
    title: "Lakers win NBA championship 2026?",
    yes: 28, no: 72, timeLeft: "4mo left", progress: 12,
    thumb: "assets/thumbs/lakers.jpg",
    inWallet: true,
  },
  {
    category: "sport",
    source: "BetZone", volume: "$3.2M", delta: "-1.1%",
    title: "Manchester City win Premier League?",
    yes: 68, no: 32, timeLeft: "29d left", progress: 51,
    thumb: "assets/thumbs/man-city.jpg",
  },
  {
    category: "sport",
    source: "Polymarket", volume: "$2.1M", delta: "+2.7%",
    title: "Real Madrid reach UCL final?",
    yes: 47, no: 53, timeLeft: "44d left", progress: 36,
    thumb: "assets/thumbs/real-madrid.jpg",
  },
  {
    category: "sport",
    source: "Kalshi", volume: "$1.6M", delta: "+0.9%",
    title: "Verstappen wins F1 2026 title?",
    yes: 71, no: 29, timeLeft: "7mo left", progress: 22,
    thumb: "assets/thumbs/verstappen.jpg",
  },
  {
    category: "sport",
    source: "BetZone", volume: "$8.4M", delta: "-3.2%",
    title: "Argentina wins World Cup 2026?",
    yes: 18, no: 82, timeLeft: "1y 2mo left", progress: 8,
    thumb: "assets/thumbs/argentina-wc.jpg",
  },
  {
    category: "sport",
    source: "Polymarket", volume: "$720k", delta: "+1.4%",
    title: "Alcaraz wins Roland Garros 2026?",
    yes: 54, no: 46, timeLeft: "67d left", progress: 28,
    thumb: "assets/thumbs/alcaraz.jpg",
  },

  // ===== Crypto =====
  {
    category: "crypto",
    source: "Kalshi", volume: "$2.3M", delta: "-0.8%",
    title: "Bitcoin above $120k by year end?",
    yes: 41, no: 59, timeLeft: "62d left", progress: 18,
    thumb: "assets/thumbs/bitcoin.jpg",
    inWallet: true,
  },
  {
    category: "crypto",
    source: "Augur", volume: "$640k", delta: "+8.9%",
    title: "ETH/BTC ratio above 0.05 by July?",
    yes: 33, no: 67, timeLeft: "14d 2h left", progress: 78,
    thumb: "assets/thumbs/eth-btc.jpg",
  },
  {
    category: "crypto",
    source: "Polymarket", volume: "$4.2M", delta: "+12.3%",
    title: "Solana above $300 before July?",
    yes: 22, no: 78, timeLeft: "76d left", progress: 24,
    thumb: "assets/thumbs/solana.jpg",
  },
  {
    category: "crypto",
    source: "Kalshi", volume: "$1.8M", delta: "-2.1%",
    title: "ETH ETF approved by SEC in Q3?",
    yes: 64, no: 36, timeLeft: "5mo left", progress: 31,
    thumb: "assets/thumbs/eth-etf.jpg",
  },
  {
    category: "crypto",
    source: "Augur", volume: "$420k", delta: "+0.5%",
    title: "Coinbase stock above $400 this year?",
    yes: 38, no: 62, timeLeft: "8mo left", progress: 14,
    thumb: "assets/thumbs/coinbase.jpg",
  },

  // ===== Economy / Macro =====
  {
    category: "economy",
    source: "Polymarket", volume: "$12.1M", delta: "+1.2%",
    title: "Fed rate cut in December?",
    yes: 74, no: 26, timeLeft: "21d 9h left", progress: 32,
    thumb: "assets/thumbs/fed-rate.jpg",
    inWallet: true,
  },
  {
    category: "economy",
    source: "Polymarket", volume: "$15.2M", delta: "+0.6%",
    title: "S&P 500 closes above 6500 by Q3?",
    yes: 48, no: 52, timeLeft: "5mo left", progress: 38,
    thumb: "assets/thumbs/sp500.jpg",
  },
  {
    category: "economy",
    source: "Kalshi", volume: "$2.4M", delta: "-1.9%",
    title: "Gold tops $3,200/oz this month?",
    yes: 31, no: 69, timeLeft: "16d left", progress: 53,
    thumb: "assets/thumbs/gold.jpg",
  },

  // ===== Tech =====
  {
    category: "tech",
    source: "Polymarket", volume: "$5.7M", delta: "-2.4%",
    title: "SpaceX launches Starship V3 this quarter?",
    yes: 55, no: 45, timeLeft: "37d left", progress: 42,
    thumb: "assets/thumbs/spacex.jpg",
    inWallet: true,
  },
  {
    category: "tech",
    source: "Kalshi", volume: "$1.4M", delta: "+0.4%",
    title: "Apple ships AR glasses before WWDC?",
    yes: 19, no: 81, timeLeft: "2d 6h left", progress: 92,
    thumb: "assets/thumbs/apple-ar.jpg",
  },
  {
    category: "tech",
    source: "Limitless", volume: "$2.7M", delta: "+4.8%",
    title: "OpenAI releases GPT-6 before September?",
    yes: 35, no: 65, timeLeft: "126d left", progress: 30,
    thumb: "assets/thumbs/gpt6.jpg",
  },
  {
    category: "tech",
    source: "Polymarket", volume: "$1.9M", delta: "-0.6%",
    title: "Tesla full self-drive in EU 2026?",
    yes: 26, no: 74, timeLeft: "8mo left", progress: 17,
    thumb: "assets/thumbs/tesla-fsd.jpg",
  },
  {
    category: "tech",
    source: "Kalshi", volume: "$9.8M", delta: "+6.2%",
    title: "Nvidia market cap above $5T this year?",
    yes: 58, no: 42, timeLeft: "8mo left", progress: 21,
    thumb: "assets/thumbs/nvidia.jpg",
  },
  {
    category: "tech",
    source: "Augur", volume: "$340k", delta: "+1.1%",
    title: "Meta Quest 4 announced before Christmas?",
    yes: 44, no: 56, timeLeft: "7mo left", progress: 19,
    thumb: "assets/thumbs/quest4.jpg",
  },

  // ===== Politics =====
  {
    category: "politics",
    source: "Polymarket", volume: "$3.6M", delta: "+0.7%",
    title: "UK Labour wins next general election?",
    yes: 81, no: 19, timeLeft: "9mo left", progress: 11,
    thumb: "assets/thumbs/uk-labour.jpg",
    inWallet: true,
  },
  {
    category: "politics",
    source: "Kalshi", volume: "$6.2M", delta: "-1.6%",
    title: "US president approval above 50%?",
    yes: 29, no: 71, timeLeft: "11d left", progress: 87,
    thumb: "assets/thumbs/us-president.jpg",
  },

  // ===== Geopolitics (international policy + climate) =====
  {
    category: "geopolitics",
    source: "Polymarket", volume: "$1.1M", delta: "+2.0%",
    title: "EU passes AI Act amendments by June?",
    yes: 42, no: 58, timeLeft: "53d left", progress: 41,
    thumb: "assets/thumbs/eu-aiact.jpg",
  },
  {
    category: "geopolitics",
    source: "Kalshi", volume: "$2.8M", delta: "+9.1%",
    title: "Hottest July on record globally?",
    yes: 51, no: 49, timeLeft: "3mo left", progress: 47,
    thumb: "assets/thumbs/hottest-july.jpg",
  },
  {
    category: "geopolitics",
    source: "Polymarket", volume: "$1.7M", delta: "-1.4%",
    title: "Atlantic hurricane season above average?",
    yes: 59, no: 41, timeLeft: "5mo left", progress: 14,
    thumb: "assets/thumbs/hurricane.jpg",
  },
  {
    category: "geopolitics",
    source: "Kalshi", volume: "$610k", delta: "+0.2%",
    title: "La Niña confirmed by NOAA in spring?",
    yes: 36, no: 64, timeLeft: "23d left", progress: 71,
    thumb: "assets/thumbs/la-nina.jpg",
  },

  // ===== Culture / Entertainment =====
  {
    category: "culture",
    source: "BetZone", volume: "$520k", delta: "-0.3%",
    title: "Nolan's next film opens above $80M?",
    yes: 49, no: 51, timeLeft: "5mo left", progress: 25,
    thumb: "assets/thumbs/nolan-film.jpg",
  },
  {
    category: "culture",
    source: "Polymarket", volume: "$1.3M", delta: "+3.5%",
    title: "Taylor Swift announces album in 2026?",
    yes: 67, no: 33, timeLeft: "8mo left", progress: 18,
    thumb: "assets/thumbs/taylor-swift.jpg",
  },
  {
    category: "culture",
    source: "Limitless", volume: "$880k", delta: "+0.8%",
    title: "Bad Bunny tour grosses over $500M?",
    yes: 73, no: 27, timeLeft: "6mo left", progress: 33,
    thumb: "assets/thumbs/bad-bunny.jpg",
    inWallet: true,
  },
];

/* =========================================================================
   NOT SUPPORTED BY VARLA — multi-event + single-event markets.
   Multi-event markets carry an `options` array (one row per candidate).
   Single-event markets carry a binary `chance` percentage and render a
   chance-arc gauge with two large YES / NO buttons.
   ========================================================================= */
const unsupportedMarkets = [
  // ===== Multi-event =====
  {
    type: "multi", category: "politics",
    source: "Polymarket", volume: "$697K",
    title: "Peru Presidential Election Winner",
    thumb: "assets/thumbs/peru-election.jpg",
    options: [
      { name: "Keiko Fujimori", pct: 64 },
      { name: "Roberto Sánchez Palomino", pct: 27 },
      { name: "Rafael López Aliaga", pct: 6 },
      { name: "Verónika Mendoza", pct: 3 },
    ],
  },
  {
    type: "multi", category: "sport",
    source: "Kalshi", volume: "$2.1M",
    title: "NBA MVP 2025/26",
    thumb: "assets/thumbs/lakers.jpg",
    options: [
      { name: "Nikola Jokić", pct: 38 },
      { name: "Shai Gilgeous-Alexander", pct: 31 },
      { name: "Luka Dončić", pct: 14 },
      { name: "Giannis Antetokounmpo", pct: 9 },
      { name: "Jayson Tatum", pct: 5 },
    ],
  },
  {
    type: "multi", category: "culture",
    source: "Polymarket", volume: "$1.4M",
    title: "Next James Bond Actor",
    thumb: "assets/thumbs/bond-actor.jpg",
    options: [
      { name: "Aaron Taylor-Johnson", pct: 41 },
      { name: "Henry Cavill", pct: 22 },
      { name: "Theo James", pct: 14 },
      { name: "Tom Hardy", pct: 11 },
      { name: "Idris Elba", pct: 7 },
    ],
  },
  {
    type: "multi", category: "sport",
    source: "BetZone", volume: "$5.8M",
    title: "Champions League Winner 2026",
    thumb: "assets/thumbs/real-madrid.jpg",
    options: [
      { name: "Real Madrid", pct: 28 },
      { name: "Manchester City", pct: 22 },
      { name: "Bayern Munich", pct: 17 },
      { name: "Arsenal", pct: 11 },
      { name: "PSG", pct: 9 },
      { name: "Liverpool", pct: 7 },
    ],
  },
  {
    type: "multi", category: "sport",
    source: "Kalshi", volume: "$3.6M",
    title: "F1 World Champion 2026",
    thumb: "assets/thumbs/verstappen.jpg",
    options: [
      { name: "Max Verstappen", pct: 47 },
      { name: "Lando Norris", pct: 26 },
      { name: "Oscar Piastri", pct: 14 },
      { name: "Charles Leclerc", pct: 8 },
      { name: "Lewis Hamilton", pct: 3 },
    ],
  },
  {
    type: "multi", category: "politics",
    source: "Polymarket", volume: "$4.2M",
    title: "Next UK Prime Minister",
    thumb: "assets/thumbs/uk-labour.jpg",
    options: [
      { name: "Kemi Badenoch", pct: 33 },
      { name: "Keir Starmer", pct: 29 },
      { name: "Nigel Farage", pct: 21 },
      { name: "Ed Davey", pct: 9 },
      { name: "Andy Burnham", pct: 5 },
    ],
  },
  {
    type: "multi", category: "sport",
    source: "BetZone", volume: "$2.9M",
    title: "EPL Top Scorer 2025/26",
    thumb: "assets/thumbs/man-city.jpg",
    options: [
      { name: "Erling Haaland", pct: 52 },
      { name: "Mohamed Salah", pct: 18 },
      { name: "Bukayo Saka", pct: 12 },
      { name: "Ollie Watkins", pct: 9 },
      { name: "Cole Palmer", pct: 6 },
    ],
  },
  {
    type: "multi", category: "sport",
    source: "Kalshi", volume: "$1.8M",
    title: "Australian Open 2026 Men's Winner",
    thumb: "assets/thumbs/alcaraz.jpg",
    options: [
      { name: "Jannik Sinner", pct: 42 },
      { name: "Carlos Alcaraz", pct: 36 },
      { name: "Novak Djokovic", pct: 12 },
      { name: "Daniil Medvedev", pct: 6 },
    ],
  },
  {
    type: "multi", category: "culture",
    source: "Polymarket", volume: "$910K",
    title: "Best Picture Oscar 2026",
    thumb: "assets/thumbs/oscar-bestpic.jpg",
    options: [
      { name: "The Brutalist", pct: 31 },
      { name: "Anora", pct: 24 },
      { name: "Conclave", pct: 18 },
      { name: "A Complete Unknown", pct: 11 },
      { name: "Wicked", pct: 8 },
      { name: "Emilia Pérez", pct: 6 },
    ],
  },
  {
    type: "multi", category: "culture",
    source: "Limitless", volume: "$520K",
    title: "Game of the Year 2026",
    thumb: "assets/thumbs/goty.jpg",
    options: [
      { name: "GTA VI", pct: 47 },
      { name: "Death Stranding 2", pct: 18 },
      { name: "Hollow Knight Silksong", pct: 13 },
      { name: "Monster Hunter Wilds", pct: 12 },
      { name: "Ghost of Yōtei", pct: 6 },
      { name: "Borderlands 4", pct: 4 },
    ],
  },
  {
    type: "multi", category: "culture",
    source: "Polymarket", volume: "$760K",
    title: "Eurovision 2026 Winner",
    thumb: "assets/thumbs/eurovision.jpg",
    options: [
      { name: "Sweden", pct: 22 },
      { name: "France", pct: 19 },
      { name: "Switzerland", pct: 16 },
      { name: "Italy", pct: 14 },
      { name: "Estonia", pct: 11 },
      { name: "Norway", pct: 9 },
      { name: "Israel", pct: 6 },
      { name: "Germany", pct: 3 },
    ],
  },
  {
    type: "multi", category: "sport",
    source: "BetZone", volume: "$14.2M",
    title: "Super Bowl LX Winner",
    thumb: "assets/thumbs/superbowl.jpg",
    options: [
      { name: "Kansas City Chiefs", pct: 24 },
      { name: "Buffalo Bills", pct: 18 },
      { name: "Philadelphia Eagles", pct: 15 },
      { name: "Detroit Lions", pct: 13 },
      { name: "San Francisco 49ers", pct: 11 },
      { name: "Baltimore Ravens", pct: 10 },
      { name: "Houston Texans", pct: 9 },
    ],
  },
  {
    type: "multi", category: "tech",
    source: "Kalshi", volume: "$3.4M",
    title: "First lab to declare AGI",
    thumb: "assets/thumbs/agi-lab.jpg",
    options: [
      { name: "OpenAI", pct: 36 },
      { name: "Anthropic", pct: 27 },
      { name: "Google DeepMind", pct: 21 },
      { name: "xAI", pct: 9 },
      { name: "Meta", pct: 4 },
      { name: "Mistral", pct: 3 },
    ],
  },
  {
    type: "multi", category: "sport",
    source: "Polymarket", volume: "$11.4M",
    title: "World Cup 2026 Winner",
    thumb: "assets/thumbs/argentina-wc.jpg",
    options: [
      { name: "Argentina", pct: 19 },
      { name: "Brazil", pct: 17 },
      { name: "France", pct: 16 },
      { name: "Spain", pct: 14 },
      { name: "England", pct: 11 },
      { name: "Germany", pct: 8 },
      { name: "Portugal", pct: 7 },
    ],
  },
  {
    type: "multi", category: "culture",
    source: "Limitless", volume: "$640K",
    title: "Top Pop Album of 2026",
    thumb: "assets/thumbs/taylor-swift.jpg",
    options: [
      { name: "Taylor Swift", pct: 38 },
      { name: "Bad Bunny", pct: 21 },
      { name: "The Weeknd", pct: 14 },
      { name: "Billie Eilish", pct: 11 },
      { name: "Olivia Rodrigo", pct: 9 },
    ],
  },
  {
    type: "multi", category: "economy",
    source: "Kalshi", volume: "$8.7M",
    title: "Next Fed rate decision",
    thumb: "assets/thumbs/fed-rate.jpg",
    options: [
      { name: "Hold", pct: 51 },
      { name: "Cut 25bp", pct: 36 },
      { name: "Cut 50bp", pct: 9 },
      { name: "Hike 25bp", pct: 4 },
    ],
  },
  {
    type: "multi", category: "politics",
    source: "Polymarket", volume: "$6.1M",
    title: "US Senate control after midterms",
    thumb: "assets/thumbs/us-president.jpg",
    options: [
      { name: "Republican majority", pct: 56 },
      { name: "Democratic majority", pct: 39 },
      { name: "50-50 tie", pct: 5 },
    ],
  },
  {
    type: "multi", category: "crypto",
    source: "Augur", volume: "$580K",
    title: "Next crypto ETF approved by SEC",
    thumb: "assets/thumbs/eth-etf.jpg",
    options: [
      { name: "Solana spot ETF", pct: 44 },
      { name: "XRP spot ETF", pct: 27 },
      { name: "Cardano spot ETF", pct: 12 },
      { name: "Avalanche spot ETF", pct: 9 },
      { name: "Doge spot ETF", pct: 8 },
    ],
  },
  {
    type: "multi", category: "geopolitics",
    source: "Polymarket", volume: "$420K",
    title: "First country to pass major AI law in 2026",
    thumb: "assets/thumbs/eu-aiact.jpg",
    options: [
      { name: "United Kingdom", pct: 32 },
      { name: "Japan", pct: 24 },
      { name: "Canada", pct: 18 },
      { name: "South Korea", pct: 14 },
      { name: "Australia", pct: 12 },
    ],
  },
  {
    type: "multi", category: "culture",
    source: "Limitless", volume: "$1.1M",
    title: "Highest-grossing concert tour of 2026",
    thumb: "assets/thumbs/bad-bunny.jpg",
    options: [
      { name: "Bad Bunny", pct: 36 },
      { name: "Coldplay", pct: 24 },
      { name: "Taylor Swift", pct: 18 },
      { name: "BTS", pct: 13 },
      { name: "Beyoncé", pct: 9 },
    ],
  },

  // ===== Single-event =====
  {
    type: "single", category: "crypto",
    source: "Polymarket", volume: "$631K",
    title: "Will Bitcoin dip to $75,000 by December?",
    chance: 39,
    thumb: "assets/thumbs/bitcoin.jpg",
  },
  {
    type: "single", category: "tech",
    source: "Kalshi", volume: "$2.4M",
    title: "Will SpaceX land humans on Mars by 2027?",
    chance: 8,
    thumb: "assets/thumbs/spacex.jpg",
  },
  {
    type: "single", category: "tech",
    source: "Polymarket", volume: "$5.2M",
    title: "Nvidia hits $5T market cap this year?",
    chance: 62,
    thumb: "assets/thumbs/nvidia.jpg",
  },
  {
    type: "single", category: "tech",
    source: "Kalshi", volume: "$1.6M",
    title: "OpenAI releases GPT-6 before September?",
    chance: 27,
    thumb: "assets/thumbs/gpt6.jpg",
  },
  {
    type: "single", category: "economy",
    source: "Polymarket", volume: "$8.9M",
    title: "Will the US enter recession in 2026?",
    chance: 31,
    thumb: "assets/thumbs/sp500.jpg",
  },
];

/* ------------------------------------------------------------------------- */

const grid = document.getElementById("market-grid");
const gridUnsupported = document.getElementById("market-grid-unsupported");
const template = document.getElementById("market-card-template");
const multiTemplate = document.getElementById("market-card-multi-template");
const optionTemplate = document.getElementById("market-option-template");
const singleTemplate = document.getElementById("market-card-single-template");

/** Build the thumbnail <img> element for a market. */
function buildThumb(m) {
  const img = document.createElement("img");
  img.className = "market-card__thumb";
  img.src = m.thumb;
  img.alt = "";
  img.loading = "lazy";
  return img;
}

/* ---- Combined filter state: category chip + search query + segment + sort.
   All apply at the same time — a card is shown only if it matches all.
   Declared early so render() can read `filterState.sort` on first paint. */
const filterState = { category: "all", query: "", inWallet: false, segment: "supported", sort: "newest" };

/* Volume strings ("$4.8M", "$890K", "$697K") → number, for sort comparison. */
function parseVolume(s) {
  if (!s) return 0;
  const m = s.match(/\$([\d.]+)\s*([KMB]?)/i);
  if (!m) return 0;
  const num = parseFloat(m[1]) || 0;
  const mult = { K: 1e3, M: 1e6, B: 1e9 }[m[2].toUpperCase()] || 1;
  return num * mult;
}

/* timeLeft strings ("8d 4h left", "29d left", "5mo left", "1y 2mo left")
   → minutes-remaining number. Markets without timeLeft (e.g. unsupported)
   are sorted last via Number.MAX_SAFE_INTEGER. */
function parseTimeLeft(s) {
  if (!s) return Number.MAX_SAFE_INTEGER;
  const factors = { y: 525600, mo: 43200, d: 1440, h: 60, m: 1 };
  let total = 0;
  // `mo` is matched before `m` so "5mo" doesn't read as "5m + o".
  for (const [, n, u] of s.matchAll(/(\d+)\s*(mo|y|d|h|m)/g)) {
    total += parseInt(n, 10) * (factors[u] || 0);
  }
  return total || Number.MAX_SAFE_INTEGER;
}

/* Return a copy of `arr` ordered per the active sort. The original array
   stays untouched so switching back to "Newest" restores natural order. */
function getSortedMarkets(arr) {
  const sort = filterState.sort;
  if (sort === "newest" || !sort) return arr;
  const copy = [...arr];
  if (sort === "oldest") return copy.reverse();
  if (sort === "volume") {
    return copy.sort((a, b) => parseVolume(b.volume) - parseVolume(a.volume));
  }
  if (sort === "ending-soon") {
    return copy.sort((a, b) => parseTimeLeft(a.timeLeft) - parseTimeLeft(b.timeLeft));
  }
  return arr;
}

/** Wire up a custom scroll-thumb overlay for an option list.
 *  Sizes and positions the thumb based on scroll progress, hides it when
 *  the list doesn't overflow, and flashes `is-visible` while the user is
 *  actively scrolling so the thumb appears even without hovering. */
function attachScrollThumb(list, thumb) {
  if (!list || !thumb) return;
  let hideTimer = null;

  const update = () => {
    const visible = list.clientHeight;
    const total = list.scrollHeight;
    if (total <= visible + 1) {
      thumb.hidden = true;
      return;
    }
    thumb.hidden = false;
    const thumbHeight = Math.max((visible / total) * visible, 16);
    const maxScroll = total - visible;
    const range = visible - thumbHeight;
    const top = maxScroll > 0 ? (list.scrollTop / maxScroll) * range : 0;
    thumb.style.height = `${thumbHeight}px`;
    thumb.style.transform = `translateY(${top}px)`;
  };

  list.addEventListener("scroll", () => {
    update();
    thumb.classList.add("is-visible");
    clearTimeout(hideTimer);
    hideTimer = setTimeout(() => thumb.classList.remove("is-visible"), 700);
  });

  // Recompute on size changes (e.g. font load, layout shifts).
  if (typeof ResizeObserver !== "undefined") {
    new ResizeObserver(update).observe(list);
  }
  update();
}

function render() {
  const fragment = document.createDocumentFragment();

  for (const m of getSortedMarkets(markets)) {
    const node = template.content.firstElementChild.cloneNode(true);

    // Tag the card with its category + wallet flag so the filters can
    // show/hide it.
    node.dataset.category = m.category;
    node.dataset.inWallet = m.inWallet ? "true" : "false";

    // Wallet chip is hidden by default in the template; reveal it for
    // markets the user "owns".
    if (m.inWallet) {
      const chip = node.querySelector(".wallet-chip");
      if (chip) chip.hidden = false;
    }

    // Thumbnail — replace the placeholder host element
    const host = node.querySelector(".market-card__thumb-host");
    host.replaceWith(buildThumb(m));

    // Meta row
    node.querySelector(".market-card__source").textContent =
      `${m.source.toUpperCase()} • VOL ${m.volume}`;

    const deltaEl = node.querySelector(".market-card__delta");
    deltaEl.textContent = m.delta;
    if (m.delta.trim().startsWith("-")) {
      deltaEl.classList.add("is-negative");
    }

    // Title
    node.querySelector(".market-card__title").textContent = m.title;

    // Odds bar — flip emphasis when NO is leading (yes < 50%)
    const oddsBar = node.querySelector(".odds-bar");
    if (m.yes < 50) {
      oddsBar.classList.add("is-no-leading");
    }

    const yesLabel = node.querySelector(".odds-bar__side--yes .odds-bar__label");
    const noLabel = node.querySelector(".odds-bar__side--no .odds-bar__label");
    yesLabel.textContent = `YES • ${m.yes}%`;
    noLabel.textContent = `NO • ${m.no}%`;
    node.querySelector(".odds-bar__side--yes").style.setProperty(
      "--yes-pct",
      `${m.yes}%`
    );

    // Footer
    node.querySelector(".market-card__time").textContent = m.timeLeft;
    node.querySelector(".progress__fill").style.setProperty(
      "--progress-pct",
      `${m.progress}%`
    );

    fragment.appendChild(node);
  }

  grid.replaceChildren(fragment);
}

/* Render the not-supported tab — picks a multi-event or single-event
   template per market based on `m.type`. */
function renderUnsupported() {
  const fragment = document.createDocumentFragment();

  for (const m of getSortedMarkets(unsupportedMarkets)) {
    const tpl = m.type === "single" ? singleTemplate : multiTemplate;
    const node = tpl.content.firstElementChild.cloneNode(true);

    node.dataset.category = m.category;
    node.dataset.inWallet = "false";
    node.dataset.type = m.type || "multi";

    // Thumbnail
    const host = node.querySelector(".market-card__thumb-host");
    host.replaceWith(buildThumb(m));

    // Title
    node.querySelector(".market-card__title").textContent = m.title;

    // Footer volume — Figma shows just "$XXX VOL." with no source.
    node.querySelector(".market-card__volume").textContent = `${m.volume} VOL.`;

    if (m.type === "single") {
      // Chance arc — Figma 16164:203252 is a 180° arc with radius 26 in a
      // 60×41 frame, so the visible length is π × 26 ≈ 81.68. Dasharray
      // sets the filled fraction so the arc represents `m.chance` %.
      const arcLength = Math.PI * 26;
      const filled = (arcLength * m.chance) / 100;
      node.querySelector("[data-chance-pct]").textContent = `${m.chance}%`;
      const fillPath = node.querySelector("[data-chance-arc-fill]");
      fillPath.setAttribute("stroke-dasharray", `${filled} ${arcLength}`);
      // Arc colour follows the chance value: accent-green-lime at ≥50%,
      // accent-red below — both at 60% opacity so the stroke reads softer
      // against the dark card.
      const stroke = m.chance >= 50
        ? "rgba(195, 227, 130, 0.6)"
        : "rgba(225, 71, 71, 0.6)";
      fillPath.setAttribute("stroke", stroke);
    } else {
      // Multi-event — clone an option row per candidate. The list scrolls
      // when it has more than ~2 options; the absolute scroll thumb lives
      // in the wrapper next to the list (see `attachScrollThumb`).
      const list = node.querySelector("[data-option-list]");
      const thumb = node.querySelector("[data-option-thumb]");
      for (const opt of m.options) {
        const row = optionTemplate.content.firstElementChild.cloneNode(true);
        row.querySelector(".option-row__name").textContent = opt.name;
        row.querySelector(".option-row__pct").textContent = `${opt.pct}%`;
        list.appendChild(row);
      }
      attachScrollThumb(list, thumb);
    }

    fragment.appendChild(node);
  }

  gridUnsupported.replaceChildren(fragment);
}

render();
renderUnsupported();
document.body.dataset.tab = filterState.segment;

/* =========================================================================
   Toolbar interactivity
   ========================================================================= */
function singleSelect(groupSelector, itemSelector, onSelect) {
  const items = document.querySelectorAll(`${groupSelector} ${itemSelector}`);
  for (const item of items) {
    item.addEventListener("click", () => {
      for (const sibling of items) {
        const isMe = sibling === item;
        sibling.classList.toggle("is-active", isMe);
        if (sibling.getAttribute("role") === "tab") {
          sibling.setAttribute("aria-selected", String(isMe));
        }
      }
      onSelect?.(item);
    });
  }
}


function escapeRegex(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function highlightedHTML(text, query) {
  if (!query) return text;
  // Escape any < > & in the source text first (we're about to set innerHTML)
  const safe = text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
  const re = new RegExp(`(${escapeRegex(query)})`, "gi");
  return safe.replace(re, "<mark>$1</mark>");
}

function applyFilters() {
  const q = filterState.query.trim();
  const qLower = q.toLowerCase();
  const cat = filterState.category;
  // Only filter the active grid — the inactive one is hidden anyway and
  // its state will be re-applied when the user switches back to it.
  const activeGrid = filterState.segment === "supported" ? grid : gridUnsupported;
  for (const card of activeGrid.querySelectorAll(".market-card")) {
    const catOk = cat === "all" || card.dataset.category === cat;

    const titleEl = card.querySelector(".market-card__title");
    const sourceEl = card.querySelector(".market-card__source");
    // Use textContent so any previous <mark> wrappers are stripped first.
    const titleText = titleEl?.textContent || "";
    const sourceText = sourceEl?.textContent || "";

    const titleMatches = titleText.toLowerCase().includes(qLower);
    const sourceMatches = sourceText.toLowerCase().includes(qLower);
    const queryOk = q === "" || titleMatches || sourceMatches;
    const walletOk = !filterState.inWallet || card.dataset.inWallet === "true";

    card.hidden = !(catOk && queryOk && walletOk);

    // Repaint the highlight (or restore plain text) on each pass.
    if (titleEl) {
      titleEl.innerHTML = q && titleMatches
        ? highlightedHTML(titleText, q)
        : titleText;
    }
    if (sourceEl) {
      sourceEl.innerHTML = q && sourceMatches
        ? highlightedHTML(sourceText, q)
        : sourceText;
    }
  }
}

/* ---- Reusable filter-dropdown (button + popover with checkmark items).
   Mirrors the leaderboard-list's setupDropdown — open/close on toggle,
   sync the trigger label with the picked option, close on outside click
   or Escape. `toggleable` re-clicks the active item to clear it; off
   here because the sort always has a selection. */
function setupDropdown(dropdown, { onSelect, toggleable = false } = {}) {
  if (!dropdown) return;
  const toggle = dropdown.querySelector("[data-dropdown-toggle]");
  const menu = dropdown.querySelector(".filter-menu");
  const label = dropdown.querySelector(".filter-btn__label");
  const items = dropdown.querySelectorAll(".filter-menu__item");
  const defaultLabel = label.textContent;

  const preselected = dropdown.querySelector(".filter-menu__item.is-selected");
  let currentValue = preselected ? preselected.dataset.value : "";

  function open() {
    menu.hidden = false;
    dropdown.dataset.open = "true";
    toggle.setAttribute("aria-expanded", "true");
  }
  function close() {
    menu.hidden = true;
    dropdown.dataset.open = "false";
    toggle.setAttribute("aria-expanded", "false");
  }
  function setSelection(value) {
    currentValue = value;
    items.forEach((it) => {
      it.classList.toggle("is-selected", it.dataset.value === value);
    });
    if (value) {
      const matched = dropdown.querySelector(
        `.filter-menu__item[data-value="${value}"] .filter-menu__label`
      );
      label.textContent = matched ? matched.textContent : defaultLabel;
    } else {
      label.textContent = defaultLabel;
    }
    if (onSelect) onSelect(value);
  }

  toggle.addEventListener("click", () => {
    menu.hidden ? open() : close();
  });

  items.forEach((item) => {
    item.addEventListener("click", () => {
      const value = item.dataset.value;
      const next = toggleable && value === currentValue ? "" : value;
      setSelection(next);
      close();
    });
  });

  document.addEventListener("click", (e) => {
    if (!dropdown.contains(e.target)) close();
  });
  document.addEventListener("keydown", (e) => {
    if (e.key === "Escape" && !menu.hidden) close();
  });

  return { setSelection, open, close };
}

/* Wire the sort dropdown — re-renders the active grid with the new order
   and re-applies the search/category/wallet filters on top. */
const sortDropdown = setupDropdown(
  document.querySelector('.filter-dropdown[data-filter="sort"]'),
  {
    toggleable: false,
    onSelect: (value) => {
      filterState.sort = value || "newest";
      render();
      renderUnsupported();
      applyFilters();
    },
  }
);

/* ---- Segments — toggle which grid is visible.
   Filters still apply to whichever grid is active; the inactive grid is
   removed from the layout via `hidden` so the page reflows correctly. */
singleSelect(".segments", ".segment", (chip) => {
  const seg = chip.dataset.segment;
  filterState.segment = seg;
  const isSupported = seg === "supported";
  grid.hidden = !isSupported;
  gridUnsupported.hidden = isSupported;
  // Drive CSS that hides supported-only sort options when on the
  // not-supported tab.
  document.body.dataset.tab = seg;
  // If user was sorting by a supported-only key (e.g. "ending-soon")
  // and switched to not-supported, fall back to "newest".
  if (!isSupported && filterState.sort === "ending-soon") {
    sortDropdown?.setSelection("newest");
  }
  applyFilters();
});

singleSelect(".filters", ".filter", (chip) => {
  filterState.category = chip.dataset.filter;
  applyFilters();
});

/* ---- Search input — filters by title + source, live as the user types. */
const searchInput = document.querySelector(".search-row__input input");
searchInput?.addEventListener("input", (e) => {
  filterState.query = e.target.value;
  applyFilters();
});

/* ---- "In wallet" toggle — when on, only show cards whose `inWallet`
   flag is true. The wallet chip itself stays visible regardless. */
const walletToggleInput = document.querySelector(".switch input[type='checkbox']");
walletToggleInput?.addEventListener("change", () => {
  filterState.inWallet = walletToggleInput.checked;
  applyFilters();
});

/* ---- Refresh button — shows the dim+spinner overlay over the grid for
   ~900ms, then re-renders the cards and re-applies the active filters. */
const refreshBtn = document.querySelector("[data-refresh]");
const loadingOverlay = document.getElementById("grid-loading");
refreshBtn?.addEventListener("click", () => {
  if (refreshBtn.classList.contains("is-loading")) return;
  refreshBtn.classList.add("is-loading");
  loadingOverlay?.classList.add("is-active");
  setTimeout(() => {
    render();
    renderUnsupported();
    applyFilters();
    refreshBtn.classList.remove("is-loading");
    loadingOverlay?.classList.remove("is-active");
  }, 900);
});

/* =========================================================================
   Wallet tooltip — opens on click of the help icon, closes on close-btn
   click, "Got it"/"Skip" click, outside click, or Escape key.
   Positioned with `position: fixed` based on the trigger's bounding rect
   so it escapes the sticky toolbar's clipping context.
   ========================================================================= */
const tooltip = document.getElementById("wallet-tooltip");
const tooltipTrigger = document.querySelector("[data-tooltip-trigger]");

function openTooltip() {
  if (!tooltip || !tooltipTrigger) return;
  const rect = tooltipTrigger.getBoundingClientRect();
  tooltip.hidden = false;
  // Position below the trigger, right-aligned to the icon. Re-measure
  // tooltip dimensions after it's visible so we can clamp inside the viewport.
  const ttRect = tooltip.getBoundingClientRect();
  const margin = 8;
  let left = rect.right - ttRect.width;
  let top = rect.bottom + 8;
  // Clamp to viewport
  left = Math.max(margin, Math.min(left, window.innerWidth - ttRect.width - margin));
  // If not enough room below, flip above
  if (top + ttRect.height > window.innerHeight - margin) {
    top = rect.top - ttRect.height - 8;
  }
  tooltip.style.left = `${left}px`;
  tooltip.style.top = `${top}px`;
}

function closeTooltip() {
  if (tooltip) tooltip.hidden = true;
}

tooltipTrigger?.addEventListener("click", (e) => {
  e.stopPropagation();
  if (tooltip?.hidden) openTooltip();
  else closeTooltip();
});

tooltip?.querySelectorAll("[data-tooltip-close]").forEach((el) => {
  el.addEventListener("click", closeTooltip);
});

document.addEventListener("click", (e) => {
  if (!tooltip || tooltip.hidden) return;
  if (tooltip.contains(e.target) || tooltipTrigger?.contains(e.target)) return;
  closeTooltip();
});

document.addEventListener("keydown", (e) => {
  if (e.key === "Escape") closeTooltip();
});
